version: 2

orbs:
  welcome: circleci/welcome-orb@0.3.1

workflows:
  Welcome:
    jobs:
      - deploy-job
      - welcome/run

jobs:
  deploy-job:
    steps:
      - add_ssh_keys:
          fingerprints:
            - "50:5b:2a:50:41:56:a8:7f:16:1e:4e:12:48:f1:93:2c"

